name: Trigger site rebuild

on: [push]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Install hunspell
      run: |
        sudo apt-get update
        sudo apt-get install python-dev-is-python3 
        sudo apt-get install libhunspell-dev
        sudo pip install hunspell
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@0.47.0

  dispatch:
    runs-on: ubuntu-latest
    needs: spellcheck
    steps:
    - uses: defold/repository-dispatch@1.2.1
      with:
        repo: defold/defold.github.io
        token: ${{ secrets.SERVICES_GITHUB_TOKEN }}
        user: services@defold.se
        action: docs
